#LetsFly by Rexy.
console_error_message: '&8(&c&l!&8) &c&lPlease Dont Use Me In Console!'
no_perm: '&8(&c&l!&8) &c&lNo Perms!'

flying_enabled: '&8(&a&l!&8) &a&lFlying Enabled!'
flying_disabled: '&8(&a&l!&8) &a&lFlying Disabled!'